<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>20907276</PostId><Url>http://stackoverflow.com/questions/20907276</Url><Stack><Type>AuthCanceled</Type><Message>Authentication process canceled</Message><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/django/core/handlers/base.py</File><Line>114</Line><Method>get_response</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py</File><Line>57</Line><Method>wrapped_view</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/apps/django_app/utils.py</File><Line>45</Line><Method>wrapper</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/apps/django_app/views.py</File><Line>21</Line><Method>complete</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/actions.py</File><Line>54</Line><Method>do_complete</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/strategies/base.py</File><Line>62</Line><Method>complete</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/backends/facebook.py</File><Line>63</Line><Method>auth_complete</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/backends/facebook.py</File><Line>56</Line><Method>process_error</Method></Frame><Frame><File>/home/vera/virtualenv/myapp/local/lib/python2.7/site-packages/social/backends/oauth.py</File><Line>312</Line><Method>process_error</Method></Frame></Stack></Post></Posts>