<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>21629007</PostId><Url>http://stackoverflow.com/questions/21629007</Url><Stack><Type>AutoReconnect</Type><Message>could not connect to localhost:27017: [Errno 10061] No connection could be made because the target machine actively refused it</Message><Frame><File>C:\Python27\lib\site-packages\werkzeug\serving.py</File><Line>177</Line><Method>run_wsgi</Method></Frame><Frame><File>C:\Python27\lib\site-packages\werkzeug\serving.py</File><Line>165</Line><Method>execute</Method></Frame><Frame><File>C:\Python27\lib\site-packages\flask\app.py</File><Line>1836</Line><Method>__call__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\flask\app.py</File><Line>1820</Line><Method>wsgi_app</Method></Frame><Frame><File>C:\Python27\lib\site-packages\flask\app.py</File><Line>1410</Line><Method>handle_exception</Method></Frame><Frame><File>D:\proj\beardev\mcp\common\routes.py</File><Line>101</Line><Method>page_error</Method></Frame></Stack></Post></Posts>