<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>22042212</PostId><Url>http://stackoverflow.com/questions/22042212</Url><Stack><Type>ClientException</Type><Message>Account HEAD failed: http://localhost:8080:8080/v1/AUTH_myaccount 404 Not Found</Message><Frame><File>/usr/lib/python2.6/site-packages/swiftclient/client.py</File><Line>1192</Line><Method>_retry</Method></Frame><Frame><File>/usr/lib/python2.6/site-packages/swiftclient/client.py</File><Line>469</Line><Method>head_account</Method></Frame></Stack></Post><Post><PostId>22113136</PostId><Url>http://stackoverflow.com/questions/22113136</Url><Stack><Type>ClientException</Type><Message>Endpoint for object-store not found - have you specified a region?</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>1184</Line><Method>_retry</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>1158</Line><Method>get_auth</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>345</Line><Method>get_auth</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>293</Line><Method>get_keystoneclient_2_0</Method></Frame></Stack></Post><Post><PostId>23251146</PostId><Url>http://stackoverflow.com/questions/23251146</Url><Stack><Type>ClientException</Type><Message>Object HEAD failed: http://10.249.238.135:9024:9024/v1/rjm-vnx-namespace01/container1/test_file01.txt 404 Not Found</Message><Frame><File>pyshell#121</File><Line>1</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>1279</Line><Method>head_object</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>1189</Line><Method>_retry</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/swiftclient/client.py</File><Line>853</Line><Method>head_object</Method></Frame></Stack></Post></Posts>