<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>685589</PostId><Url>http://stackoverflow.com/questions/685589</Url><Stack><Type>COMError</Type><Message>(-2147352567, 'Exception occurred.', (None, None, None, 0, None))</Message><Frame><File>pyshell#34</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:/Documents and Settings/cvmne250/Desktop/temp.py</File><Line>17</Line><Method>create_querytable</Method></Frame><Frame><File>G:\ISA\SPSS\comtypes\lib\comtypes\client\lazybind.py</File><Line>160</Line><Method>caller</Method></Frame><Frame><File>G:\ISA\SPSS\comtypes\lib\comtypes\automation.py</File><Line>628</Line><Method>_invoke</Method></Frame></Stack></Post><Post><PostId>18258743</PostId><Url>http://stackoverflow.com/questions/18258743</Url><Stack><Type>COMError</Type><Message>(-2147418111, 'Call was rejected by callee.', (None, None, None, 0, None))</Message><Frame><File>pyshell#4</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>153</Line><Method>prompt</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>65</Line><Method>doc</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>54</Line><Method>app</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\__init__.py</File><Line>183</Line><Method>GetActiveObject</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\__init__.py</File><Line>188</Line><Method>_manage</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\__init__.py</File><Line>112</Line><Method>GetBestInterface</Method></Frame><Frame><File>pyshell#4</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>153</Line><Method>prompt</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>65</Line><Method>doc</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>59</Line><Method>app</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\dynamic.py</File><Line>116</Line><Method>__setattr__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\automation.py</File><Line>643</Line><Method>GetIDsOfNames</Method></Frame></Stack></Post><Post><PostId>18258743</PostId><Url>http://stackoverflow.com/questions/18258743</Url><Stack><Type>COMError</Type><Message>(-2147418111, 'Call was rejected by callee.', (None, None, None, 0, None))</Message><Frame><File>pyshell#4</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>153</Line><Method>prompt</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>65</Line><Method>doc</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>54</Line><Method>app</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\__init__.py</File><Line>183</Line><Method>GetActiveObject</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\__init__.py</File><Line>188</Line><Method>_manage</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\__init__.py</File><Line>112</Line><Method>GetBestInterface</Method></Frame><Frame><File>pyshell#4</File><Line>1</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>153</Line><Method>prompt</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>65</Line><Method>doc</Method></Frame><Frame><File>C:\Python27\lib\site-packages\pyautocad\api.py</File><Line>59</Line><Method>app</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\client\dynamic.py</File><Line>116</Line><Method>__setattr__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\comtypes\automation.py</File><Line>643</Line><Method>GetIDsOfNames</Method></Frame></Stack></Post><Post><PostId>24320478</PostId><Url>http://stackoverflow.com/questions/24320478</Url><Stack><Type>COMError</Type><Message>(-2146823114, None, (u'Sorry, we couldn\u2019t find your file. Is it</Message><Frame><File>F:\py\newProj\parse.py</File><Line>8</Line><Method>module</Method></Frame></Stack></Post></Posts>