<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>4519829</PostId><Url>http://stackoverflow.com/questions/4519829</Url><Stack><Type>CommandError</Type><Message>Unknown command: u'del_hit'</Message><Frame><File>/home/vadmin/development/python/my_proj/chronograph/models.py</File><Line>213</Line><Method>handle_run</Method></Frame><Frame><File>/usr/lib/python2.6/dist-packages/django/core/management/__init__.py</File><Line>155</Line><Method>call_command</Method></Frame></Stack></Post><Post><PostId>10942171</PostId><Url>http://stackoverflow.com/questions/10942171</Url><Stack><Type>CommandError</Type><Message>Unknown command: 'parse_email'</Message><Frame><File>/bldg/tests.py</File><Line>36</Line><Method>test_submit_bldg</Method></Frame><Frame><File>django/core/management/__init__.py</File><Line>136</Line><Method>call_command</Method></Frame></Stack></Post><Post><PostId>19979934</PostId><Url>http://stackoverflow.com/questions/19979934</Url><Stack><Type>CommandError</Type><Message>One or more models did not validate:</Message><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>222</Line><Method>run_from_argv</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>255</Line><Method>execute</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>386</Line><Method>handle</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/south/management/commands/syncdb.py</File><Line>103</Line><Method>handle_noargs</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py</File><Line>161</Line><Method>call_command</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py</File><Line>37</Line><Method>new_execute</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>255</Line><Method>execute</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/south/management/commands/migrate.py</File><Line>111</Line><Method>handle</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/south/migration/__init__.py</File><Line>233</Line><Method>migrate_app</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/south/migration/migrators.py</File><Line>224</Line><Method>load_initial_data</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py</File><Line>161</Line><Method>call_command</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py</File><Line>37</Line><Method>new_execute</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>254</Line><Method>execute</Method></Frame><Frame><File>.virtualenv/lib/python2.7/site-packages/django/core/management/base.py</File><Line>285</Line><Method>validate</Method></Frame></Stack></Post></Posts>