<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>14791430</PostId><Url>http://stackoverflow.com/questions/14791430</Url><Stack><Type>ConnectionRefusedError</Type><Message>[WinError 10061] No connection could be made because the target machine actively refused it</Message><Frame><File>C:/Users/Brett/PycharmProjects/Texting/sendMessage.py</File><Line>13</Line><Method>module</Method></Frame><Frame><File>C:\Python33\lib\smtplib.py</File><Line>238</Line><Method>__init__</Method></Frame><Frame><File>C:\Python33\lib\smtplib.py</File><Line>317</Line><Method>connect</Method></Frame><Frame><File>C:\Python33\lib\smtplib.py</File><Line>288</Line><Method>_get_socket</Method></Frame><Frame><File>C:\Python33\lib\socket.py</File><Line>424</Line><Method>create_connection</Method></Frame><Frame><File>C:\Python33\lib\socket.py</File><Line>415</Line><Method>create_connection</Method></Frame></Stack></Post><Post><PostId>15978257</PostId><Url>http://stackoverflow.com/questions/15978257</Url><Stack><Type>ConnectionRefusedError</Type><Message>[WinError 10061] No connection could be made because the target machine actively refused it</Message><Frame><File>C:\Users\SIGABRT\Desktop\tcp.py</File><Line>4</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18157527</PostId><Url>http://stackoverflow.com/questions/18157527</Url><Stack><Type>ConnectionRefusedError</Type><Message>[WinError 10061] No connection could be made because the target machine actively refused it</Message><Frame><File>C:\Python33\_ROB\tor.py</File><Line>20</Line><Method>module</Method></Frame><Frame><File>C:\Python33\_ROB\tor.py</File><Line>15</Line><Method>main</Method></Frame><Frame><File>C:\Python33\lib\http\client.py</File><Line>1061</Line><Method>request</Method></Frame><Frame><File>C:\Python33\lib\http\client.py</File><Line>1099</Line><Method>_send_request</Method></Frame><Frame><File>C:\Python33\lib\http\client.py</File><Line>1057</Line><Method>endheaders</Method></Frame><Frame><File>C:\Python33\lib\http\client.py</File><Line>902</Line><Method>_send_output</Method></Frame><Frame><File>C:\Python33\lib\http\client.py</File><Line>840</Line><Method>send</Method></Frame><Frame><File>C:\Python33\lib\http\client.py</File><Line>818</Line><Method>connect</Method></Frame><Frame><File>C:\Python33\lib\socket.py</File><Line>435</Line><Method>create_connection</Method></Frame><Frame><File>C:\Python33\lib\socket.py</File><Line>426</Line><Method>create_connection</Method></Frame><Frame><File>C:\Python33\lib\socks.py</File><Line>363</Line><Method>connect</Method></Frame></Stack></Post><Post><PostId>19688932</PostId><Url>http://stackoverflow.com/questions/19688932</Url><Stack><Type>ConnectionRefusedError</Type><Message>[WinError 10061] No connection could be made because the target machine actively refused it" Error.</Message><Frame><File>C:\Users\Paul\Desktop\client.py</File><Line>12</Line><Method>s.connect((TCP_IP, TCP_PORT))</Method></Frame></Stack></Post><Post><PostId>22612071</PostId><Url>http://stackoverflow.com/questions/22612071</Url><Stack><Type>ConnectionRefusedError</Type><Message>[WinError 10061] No connection could be made because the target            machine actively refused it</Message><Frame><File>C:\Documents and Settings\kalyan\Desktop\My_creation\client.py</File><Line>21</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24745700</PostId><Url>http://stackoverflow.com/questions/24745700</Url><Stack><Type>ConnectionRefusedError</Type><Message>[Errno 111] Connection refused</Message><Frame><File>/usr/lib/python3.4/urllib/request.py</File><Line>1232</Line><Method>do_open</Method></Frame><Frame><File>/usr/lib/python3.4/http/client.py</File><Line>1065</Line><Method>request</Method></Frame><Frame><File>/usr/lib/python3.4/http/client.py</File><Line>1103</Line><Method>_send_request</Method></Frame><Frame><File>/usr/lib/python3.4/http/client.py</File><Line>1061</Line><Method>endheaders</Method></Frame><Frame><File>/usr/lib/python3.4/http/client.py</File><Line>906</Line><Method>_send_output</Method></Frame><Frame><File>/usr/lib/python3.4/http/client.py</File><Line>841</Line><Method>send</Method></Frame><Frame><File>/usr/lib/python3.4/http/client.py</File><Line>819</Line><Method>connect</Method></Frame><Frame><File>/usr/lib/python3.4/socket.py</File><Line>509</Line><Method>create_connection</Method></Frame><Frame><File>/usr/lib/python3.4/socket.py</File><Line>500</Line><Method>create_connection</Method></Frame></Stack></Post></Posts>