<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>3264257</PostId><Url>http://stackoverflow.com/questions/3264257</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>./script</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>3804727</PostId><Url>http://stackoverflow.com/questions/3804727</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>./script.py</File><Line>4</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>5054307</PostId><Url>http://stackoverflow.com/questions/5054307</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/usr/local/bin/django-startproject.py</File><Line>7</Line><Method>module</Method></Frame><Frame><File>/home/rich/src/ll-django-startproject/bin/django-startproject.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/home/rich/src/ll-django-startproject/bin/django-startproject.py</File><Line>5</Line><Method>main</Method></Frame><Frame><File>/home/rich/src/ll-django-startproject/django_startproject/management.py</File><Line>44</Line><Method>start_project</Method></Frame></Stack></Post><Post><PostId>5697305</PostId><Url>http://stackoverflow.com/questions/5697305</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/usr/lib/python2.6/multiprocessing/process.py</File><Line>232</Line><Method>_bootstrap</Method></Frame><Frame><File>/usr/lib/python2.6/multiprocessing/process.py</File><Line>88</Line><Method>run</Method></Frame><Frame><File>test.py</File><Line>5</Line><Method>f</Method></Frame></Stack></Post><Post><PostId>6104289</PostId><Url>http://stackoverflow.com/questions/6104289</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>input.py</File><Line>13</Line><Method>module</Method></Frame><Frame><File>input.py</File><Line>5</Line><Method>chooseinput</Method></Frame></Stack></Post><Post><PostId>6312819</PostId><Url>http://stackoverflow.com/questions/6312819</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>mrprompt.py</File><Line>9</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>7061772</PostId><Url>http://stackoverflow.com/questions/7061772</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/Users/shameer/Desktop/Test Programs/questions.app/Contents/Resources/script</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>7437261</PostId><Url>http://stackoverflow.com/questions/7437261</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>.git/hooks/pre-commit</File><Line>59</Line><Method>?</Method></Frame><Frame><File>.git/hooks/pre-commit</File><Line>20</Line><Method>main</Method></Frame></Stack></Post><Post><PostId>7489967</PostId><Url>http://stackoverflow.com/questions/7489967</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/usr/lib/python2.7/multiprocessing/process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>/usr/lib/python2.7/multiprocessing/process.py</File><Line>114</Line><Method>run</Method></Frame><Frame><File>/home/blah/blah/blah/blah.py</File><Line>325</Line><Method>sub_proc</Method></Frame><Frame><File>/randompathhere/eclipse/plugins/org.python.pydev_2.1.0.2011052613/PySrc/pydev_sitecustomize/sitecustomize.py</File><Line>181</Line><Method>raw_input</Method></Frame></Stack></Post><Post><PostId>8837554</PostId><Url>http://stackoverflow.com/questions/8837554</Url><Stack><Type>EOFError</Type><Message>Not enought lines in module</Message><Frame><File>stdin</File><Line>1</Line><Method>module</Method></Frame><Frame><File>stdin</File><Line>15</Line><Method>get_function_name</Method></Frame><Frame><File>stdin</File><Line>1</Line><Method>module</Method></Frame><Frame><File>stdin</File><Line>10</Line><Method>get_function_name</Method></Frame></Stack></Post><Post><PostId>8837554</PostId><Url>http://stackoverflow.com/questions/8837554</Url><Stack><Type>EOFError</Type><Message>Not enought lines in module</Message><Frame><File>stdin</File><Line>1</Line><Method>module</Method></Frame><Frame><File>stdin</File><Line>15</Line><Method>get_function_name</Method></Frame><Frame><File>stdin</File><Line>1</Line><Method>module</Method></Frame><Frame><File>stdin</File><Line>10</Line><Method>get_function_name</Method></Frame></Stack></Post><Post><PostId>9142290</PostId><Url>http://stackoverflow.com/questions/9142290</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/Users/strielok/Desktop/hello.py</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>9857677</PostId><Url>http://stackoverflow.com/questions/9857677</Url><Stack><Type>EOFError</Type><Message>EOF read where not expected</Message><Frame><File>C:\Users\Spencer\Downloads\selenium-2.20.0.tar\selenium-2.20.0\selenium-2.20.0\test</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>11346631</PostId><Url>http://stackoverflow.com/questions/11346631</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>pyshell#23</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>12547683</PostId><Url>http://stackoverflow.com/questions/12547683</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\PythonProjects\5.py</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13059062</PostId><Url>http://stackoverflow.com/questions/13059062</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/home/andrew/grive/Documents/RandomProjects/PythonStuff/HelloWorld.py</File><Line>32</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>13206438</PostId><Url>http://stackoverflow.com/questions/13206438</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2208</Line><Method>DoUpload</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1934</Line><Method>Begin</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1929</Line><Method>CloneFiles</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1841</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>403</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>543</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>293</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2758</Line><Method>GetUserCredentials</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\appcfg.py</File><Line>171</Line><Method>run_file(__file__, globals())</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\appcfg.py</File><Line>167</Line><Method>run_file</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>4322</Line><Method>main(sys.argv)</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>4313</Line><Method>main</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2599</Line><Method>Run</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>4048</Line><Method>__call__</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>3065</Line><Method>Update</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>3047</Line><Method>UpdateVersion</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2267</Line><Method>DoUpload</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2150</Line><Method>Rollback</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1841</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>403</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>543</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>293</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2758</Line><Method>GetUserCredentials</Method></Frame></Stack></Post><Post><PostId>13206438</PostId><Url>http://stackoverflow.com/questions/13206438</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2208</Line><Method>DoUpload</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1934</Line><Method>Begin</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1929</Line><Method>CloneFiles</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1841</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>403</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>543</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>293</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2758</Line><Method>GetUserCredentials</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\appcfg.py</File><Line>171</Line><Method>run_file(__file__, globals())</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\appcfg.py</File><Line>167</Line><Method>run_file</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>4322</Line><Method>main(sys.argv)</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>4313</Line><Method>main</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2599</Line><Method>Run</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>4048</Line><Method>__call__</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>3065</Line><Method>Update</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>3047</Line><Method>UpdateVersion</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2267</Line><Method>DoUpload</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2150</Line><Method>Rollback</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>1841</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>403</Line><Method>Send</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>543</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc.py</File><Line>293</Line><Method>_Authenticate</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py</File><Line>2758</Line><Method>GetUserCredentials</Method></Frame></Stack></Post><Post><PostId>13480632</PostId><Url>http://stackoverflow.com/questions/13480632</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>./teststdin.py</File><Line>25</Line><Method>module</Method></Frame><Frame><File>./teststdin.py</File><Line>8</Line><Method>test</Method></Frame></Stack></Post><Post><PostId>14167186</PostId><Url>http://stackoverflow.com/questions/14167186</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/tmp/135731949523855.py</File><Line>9</Line><Method>?</Method></Frame></Stack></Post><Post><PostId>14441519</PostId><Url>http://stackoverflow.com/questions/14441519</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/Users/jun/Documents/workspace/studyPython/test.py</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14644823</PostId><Url>http://stackoverflow.com/questions/14644823</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>prog.py</File><Line>2</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>14719117</PostId><Url>http://stackoverflow.com/questions/14719117</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Python27\last try.py</File><Line>145</Line><Method>module</Method></Frame><Frame><File>C:\Python27\last try.py</File><Line>27</Line><Method>inputPlayerLetter</Method></Frame></Stack></Post><Post><PostId>16140265</PostId><Url>http://stackoverflow.com/questions/16140265</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>../Documents/Python Programs/while.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>16279564</PostId><Url>http://stackoverflow.com/questions/16279564</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>demo.py</File><Line>2</Line><Method>name = input("Hello! What is your name?")</Method></Frame></Stack></Post><Post><PostId>16768290</PostId><Url>http://stackoverflow.com/questions/16768290</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>1st.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>17138944</PostId><Url>http://stackoverflow.com/questions/17138944</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/home/sick/Python/script1.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>/home/sick/Python/script1.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>17138944</PostId><Url>http://stackoverflow.com/questions/17138944</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/home/sick/Python/script1.py</File><Line>6</Line><Method>module</Method></Frame><Frame><File>/home/sick/Python/script1.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>17676000</PostId><Url>http://stackoverflow.com/questions/17676000</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/home/unutbu/pybin/test.py</File><Line>5</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18139502</PostId><Url>http://stackoverflow.com/questions/18139502</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/run-Lx3mHJ3G2jHRLRW9bjbX/solution.py</File><Line>4</Line><Method>t = raw_input()</Method></Frame></Stack></Post><Post><PostId>18218746</PostId><Url>http://stackoverflow.com/questions/18218746</Url><Stack><Type>EOFError</Type><Message>EOF read where object expected</Message><Frame><File>/usr/local/bin/nosetests</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/pkg_resources.py</File><Line>337</Line><Method>load_entry_point</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/pkg_resources.py</File><Line>2279</Line><Method>load_entry_point</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/pkg_resources.py</File><Line>1989</Line><Method>load</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nose/__init__.py</File><Line>1</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nose/core.py</File><Line>11</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nose/config.py</File><Line>9</Line><Method>module</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nose/plugins/__init__.py</File><Line>184</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>18883711</PostId><Url>http://stackoverflow.com/questions/18883711</Url><Stack><Type>EOFError</Type><Message>[Errno 10054] An existing connection was forcibly closed by the remote host</Message><Frame><File>string</File><Line>73</Line><Method>execInThread</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py</File><Line>196</Line><Method>__call__</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py</File><Line>71</Line><Method>syncreq</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py</File><Line>431</Line><Method>sync_request</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py</File><Line>379</Line><Method>serve</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py</File><Line>337</Line><Method>_recv</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py</File><Line>50</Line><Method>recv</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py</File><Line>166</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>18969563</PostId><Url>http://stackoverflow.com/questions/18969563</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/usr/local/lib/python2.7/threading.py</File><Line>808</Line><Method>__bootstrap_inner</Method></Frame><Frame><File>/usr/local/lib/python2.7/threading.py</File><Line>761</Line><Method>run</Method></Frame><Frame><File>/opt/devops/jenkins/workspace/MSP--Test_Agent/msp_python/lib/python2.7/site-packages/pip/index.py</File><Line>385</Line><Method>_get_queued_page</Method></Frame><Frame><File>/opt/devops/jenkins/workspace/MSP--Test_Agent/msp_python/lib/python2.7/site-packages/pip/index.py</File><Line>554</Line><Method>_get_page</Method></Frame><Frame><File>/opt/devops/jenkins/workspace/MSP--Test_Agent/msp_python/lib/python2.7/site-packages/pip/index.py</File><Line>671</Line><Method>get_page</Method></Frame><Frame><File>/opt/devops/jenkins/workspace/MSP--Test_Agent/msp_python/lib/python2.7/site-packages/pip/download.py</File><Line>181</Line><Method>__call__</Method></Frame><Frame><File>/opt/devops/jenkins/workspace/MSP--Test_Agent/msp_python/lib/python2.7/site-packages/pip/download.py</File><Line>207</Line><Method>get_response</Method></Frame></Stack></Post><Post><PostId>19172563</PostId><Url>http://stackoverflow.com/questions/19172563</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>sample.py</File><Line>6</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>19462876</PostId><Url>http://stackoverflow.com/questions/19462876</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>main.py</File><Line>2</Line><Method>a= raw_input()</Method></Frame></Stack></Post><Post><PostId>20503307</PostId><Url>http://stackoverflow.com/questions/20503307</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py</File><Line>196</Line><Method>Handle</Method></Frame><Frame><File>C:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py</File><Line>255</Line><Method>_LoadHandler</Method></Frame><Frame><File>C:\Users\la\Documents\GitHub\StorageBox\boxitnowapp\main.py</File><Line>63</Line><Method>credentials = run(FLOW, storage)</Method></Frame><Frame><File>C:\Users\la\Documents\GitHub\StorageBox\boxitnowapp\oauth2client\util.py</File><Line>132</Line><Method>positional_wrapper</Method></Frame><Frame><File>C:\Users\la\Documents\GitHub\StorageBox\boxitnowapp\oauth2client\old_run.py</File><Line>149</Line><Method>run</Method></Frame></Stack></Post><Post><PostId>21035194</PostId><Url>http://stackoverflow.com/questions/21035194</Url><Stack><Type>EOFError</Type><Message>Not enough data read. Expected: 24898 but got 2112</Message><Frame><File>./view_record.py</File><Line>30</Line><Method>module</Method></Frame><Frame><File>./view_record.py</File><Line>19</Line><Method>parse_backup_info_file</Method></Frame><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/files/records.py</File><Line>335</Line><Method>read</Method></Frame><Frame><File>/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/files/records.py</File><Line>307</Line><Method>__try_read_record</Method></Frame></Stack></Post><Post><PostId>21492049</PostId><Url>http://stackoverflow.com/questions/21492049</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>new.py</File><Line>31</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>22318185</PostId><Url>http://stackoverflow.com/questions/22318185</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>stdin</File><Line>1</Line><Method>module</Method></Frame><Frame><File>string</File><Line>1</Line><Method>f</Method></Frame></Stack></Post><Post><PostId>22392137</PostId><Url>http://stackoverflow.com/questions/22392137</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/usr/lib/python2.6/multiprocessing/process.py</File><Line>232</Line><Method>_bootstrap</Method></Frame><Frame><File>/usr/lib/python2.6/multiprocessing/process.py</File><Line>88</Line><Method>run</Method></Frame><Frame><File>atest.py</File><Line>31</Line><Method>start_fcontrol</Method></Frame><Frame><File>atest.py</File><Line>12</Line><Method>func_control</Method></Frame></Stack></Post><Post><PostId>22459847</PostId><Url>http://stackoverflow.com/questions/22459847</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Users\user\Desktop\21314</File><Line>1</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>23221505</PostId><Url>http://stackoverflow.com/questions/23221505</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>eval_get_sum.py</File><Line>3</Line><Method>module</Method></Frame><Frame><File>/eval/user_file.py</File><Line>4</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>23886864</PostId><Url>http://stackoverflow.com/questions/23886864</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/usr/lib/pymodules/python2.7/openerp/addons/web/session.py</File><Line>89</Line><Method>send</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/netsvc.py</File><Line>292</Line><Method>dispatch_rpc</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/service/web_services.py</File><Line>626</Line><Method>dispatch</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>190</Line><Method>execute_kw</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>132</Line><Method>wrapper</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>199</Line><Method>execute</Method></Frame><Frame><File>/usr/lib/pymodules/python2.7/openerp/osv/osv.py</File><Line>187</Line><Method>execute_cr</Method></Frame><Frame><File>/opt/addons_varis/google_api/google_calendar.py</File><Line>260</Line><Method>do_authorize</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/oauth2client/util.py</File><Line>132</Line><Method>positional_wrapper</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/google_api_python_client-1.2-py2.7.egg/oauth2client/tools.py</File><Line>216</Line><Method>run_flow</Method></Frame></Stack></Post><Post><PostId>24444215</PostId><Url>http://stackoverflow.com/questions/24444215</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>/home/prakashsukhwal/web2py/gluon/restricted.py</File><Line>220</Line><Method>restricted</Method></Frame><Frame><File>/home/prakashsukhwal/web2py/applications/Sensiva/controllers/default.py</File><Line>4</Line><Method>nltk.download()</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nltk/downloader.py</File><Line>644</Line><Method>download</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nltk/downloader.py</File><Line>958</Line><Method>_interactive_download</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/nltk/downloader.py</File><Line>981</Line><Method>run</Method></Frame></Stack></Post><Post><PostId>24459740</PostId><Url>http://stackoverflow.com/questions/24459740</Url><Stack><Type>EOFError</Type><Message>[Errno 10054] An existing connection was forcibly closed by the remote host</Message><Frame><File>string</File><Line>73</Line><Method>execInThread</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py</File><Line>196</Line><Method>__call__</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py</File><Line>71</Line><Method>syncreq</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py</File><Line>431</Line><Method>sync_request</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py</File><Line>379</Line><Method>serve</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py</File><Line>337</Line><Method>_recv</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py</File><Line>50</Line><Method>recv</Method></Frame><Frame><File>C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py</File><Line>166</Line><Method>read</Method></Frame></Stack></Post><Post><PostId>24736673</PostId><Url>http://stackoverflow.com/questions/24736673</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>stdin_issues.py</File><Line>19</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>24965317</PostId><Url>http://stackoverflow.com/questions/24965317</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>258</Line><Method>_bootstrap</Method></Frame><Frame><File>C:\Python27\lib\multiprocessing\process.py</File><Line>114</Line><Method>run</Method></Frame><Frame><File>C:\Users\Victor\Dropbox\Private\multiFile\main.py</File><Line>10</Line><Method>user_input</Method></Frame></Stack></Post><Post><PostId>25461344</PostId><Url>http://stackoverflow.com/questions/25461344</Url><Stack><Type>EOFError</Type><Message>EOF read where not expected</Message><Frame><File>rf2.py</File><Line>3</Line><Method>module</Method></Frame></Stack></Post><Post><PostId>25478008</PostId><Url>http://stackoverflow.com/questions/25478008</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>D:\newworkspace\SlicePython\SliceManage.py</File><Line>303</Line><Method>module</Method></Frame><Frame><File>D:\newworkspace\SlicePython\SliceManage.py</File><Line>13</Line><Method>Mainloop</Method></Frame><Frame><File>D:\newworkspace\SlicePython\SliceManage.py</File><Line>105</Line><Method>updaterecord</Method></Frame><Frame><File>D:\eclipse\eclipse-standard-luna-R-win32\eclipse\plugins\org.python.pydev_3.6.0.201406232321\pysrc\pydev_sitecustomize\sitecustomize.py</File><Line>161</Line><Method>input</Method></Frame></Stack></Post><Post><PostId>25727909</PostId><Url>http://stackoverflow.com/questions/25727909</Url><Stack><Type>EOFError</Type><Message>EOF when reading a line</Message><Frame><File>C:\Python27\Practice\1.py</File><Line>1</Line><Method>module</Method></Frame></Stack></Post></Posts>