<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>13628211</PostId><Url>http://stackoverflow.com/questions/13628211</Url><Stack><Type>LOCAL_ERROR</Type><Message>{'desc': 'Local error'}</Message><Frame><File>C:\susanta\test-sasl.py</File><Line>10</Line><Method>module</Method></Frame><Frame><File>C:\Python27\lib\site-packages\ldap\ldapobject.py</File><Line>229</Line><Method>sasl_interactive_bind_s</Method></Frame><Frame><File>C:\Python27\lib\site-packages\ldap\ldapobject.py</File><Line>99</Line><Method>_ldap_call</Method></Frame></Stack></Post></Posts>