<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>2499219</PostId><Url>http://stackoverflow.com/questions/2499219</Url><Stack><Type>NotFound</Type><Message>(404, "The path '/myAction' was not found.")</Message><Frame><File>/Library/Python/2.5/site-packages/cherrypy/_cprequest.py</File><Line>606</Line><Method>respond</Method></Frame><Frame><File>/Library/Python/2.5/site-packages/cherrypy/_cperror.py</File><Line>227</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>9526861</PostId><Url>http://stackoverflow.com/questions/9526861</Url><Stack><Type>NotFound</Type><Message>(404, "The path '/upload' was not found.")</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/cherrypy/_cperror.py</File><Line>386</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>10723604</PostId><Url>http://stackoverflow.com/questions/10723604</Url><Stack><Type>NotFound</Type><Message>&lt;</Message><Frame><File>/home/user/testing/eggs/gunicorn-0.14.3-py2.6.egg/gunicorn/workers/sync.py</File><Line>100</Line><Method>handle_request</Method></Frame><Frame><File>/home/user/testing/eggs/repoze.retry-1.0-py2.6.egg/repoze/retry/__init__.py</File><Line>90</Line><Method>__call__</Method></Frame><Frame><File>/home/user/testing/eggs/repoze.tm2-1.0b2-py2.6.egg/repoze/tm/__init__.py</File><Line>24</Line><Method>__call__</Method></Frame><Frame><File>/home/user/testing/eggs/repoze.vhm-0.14-py2.6.egg/repoze/vhm/middleware.py</File><Line>106</Line><Method>__call__</Method></Frame><Frame><File>/home/user/testing/eggs/Zope2-2.13.13-py2.6.egg/ZPublisher/WSGIPublisher.py</File><Line>255</Line><Method>publish_module</Method></Frame><Frame><File>/home/user/testing/eggs/Zope2-2.13.13-py2.6.egg/ZPublisher/WSGIPublisher.py</File><Line>185</Line><Method>publish</Method></Frame><Frame><File>/home/user/testing/eggs/Zope2-2.13.13-py2.6.egg/ZPublisher/BaseRequest.py</File><Line>518</Line><Method>traverse</Method></Frame><Frame><File>/home/user/testing/eggs/Zope2-2.13.13-py2.6.egg/ZPublisher/HTTPResponse.py</File><Line>718</Line><Method>notFoundError</Method></Frame></Stack></Post><Post><PostId>11684659</PostId><Url>http://stackoverflow.com/questions/11684659</Url><Stack><Type>NotFound</Type><Message>Invalid resource lookup data provided (mismatched type).</Message><Frame><File>...path.../resources.py</File><Line>192</Line><Method>wrapper</Method></Frame><Frame><File>...path.../resources.py</File><Line>406</Line><Method>dispatch_detail</Method></Frame><Frame><File>...path.../resources.py</File><Line>427</Line><Method>dispatch</Method></Frame><Frame><File>...path.../resources.py</File><Line>1051</Line><Method>get_detail</Method></Frame><Frame><File>...path.../resources.py</File><Line>921</Line><Method>cached_obj_get</Method></Frame><Frame><File>/...path.../resources.py</File><Line>1765</Line><Method>obj_get</Method></Frame></Stack></Post><Post><PostId>17746897</PostId><Url>http://stackoverflow.com/questions/17746897</Url><Stack><Type>NotFound</Type><Message>404: Not Found</Message><Frame><File>natuurpuntapi.py</File><Line>210</Line><Method>route_get_newsletter</Method></Frame><Frame><File>/usr/lib/python2.7/dist-packages/werkzeug/exceptions.py</File><Line>525</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>18213197</PostId><Url>http://stackoverflow.com/questions/18213197</Url><Stack><Type>NotFound</Type><Message>(404, "The path '/' was not found.")</Message><Frame><File>/Library/Python/2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/Library/Python/2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/Library/Python/2.7/site-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cperror.py</File><Line>386</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>20395565</PostId><Url>http://stackoverflow.com/questions/20395565</Url><Stack><Type>NotFound</Type><Message>(404, "The path '/abcde' was not found.")</Message><Frame><File>C:\Python27\lib\site-packages\cherrypy\_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>C:\Python27\lib\site-packages\cherrypy\lib\encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>C:\Python27\lib\site-packages\cherrypy\_cperror.py</File><Line>386</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>20553495</PostId><Url>http://stackoverflow.com/questions/20553495</Url><Stack><Type>NotFound</Type><Message>(404, "The path '/titles.html' was not found.")</Message><Frame><File>/home/dev/fbenavides/lib/python2.7/site-packages/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/home/dev/fbenavides/lib/python2.7/site-packages/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/home/dev/fbenavides/lib/python2.7/site-packages/cherrypy/_cperror.py</File><Line>386</Line><Method>__call__</Method></Frame></Stack></Post><Post><PostId>22439366</PostId><Url>http://stackoverflow.com/questions/22439366</Url><Stack><Type>NotFound</Type><Message>(404, "The path '/static/addEntry.php' was not found.")</Message><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py</File><Line>656</Line><Method>respond</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py</File><Line>188</Line><Method>__call__</Method></Frame><Frame><File>/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cperror.py</File><Line>386</Line><Method>__call__</Method></Frame></Stack></Post></Posts>