<?xml version="1.0" encoding="UTF-8"?><Posts><Post><PostId>18785893</PostId><Url>http://stackoverflow.com/questions/18785893</Url><Stack><Type>Resolver404</Type><Message>{u'path': u'', u'tried': [[</Message><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py</File><Line>85</Line><Method>run</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/handlers/wsgi.py</File><Line>255</Line><Method>__call__</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/handlers/base.py</File><Line>156</Line><Method>get_response</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/handlers/base.py</File><Line>224</Line><Method>handle_uncaught_exception</Method></Frame><Frame><File>/Users/burakk/BurakWorks/Web/Shiftf5/Development/Eclipse/shiftf5/shiftf5/urls.py</File><Line>64</Line><Method>server_error</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/shortcuts/__init__.py</File><Line>49</Line><Method>render</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/template/context.py</File><Line>179</Line><Method>__init__</Method></Frame><Frame><File>/Users/burakk/BurakWorks/Web/Shiftf5/Development/Eclipse/shiftf5/shiftf5/web/context_processors.py</File><Line>31</Line><Method>shiftf5_web</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/urlresolvers.py</File><Line>440</Line><Method>resolve</Method></Frame><Frame><File>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.5-py2.7.egg/django/core/urlresolvers.py</File><Line>334</Line><Method>resolve</Method></Frame></Stack></Post><Post><PostId>24182850</PostId><Url>http://stackoverflow.com/questions/24182850</Url><Stack><Type>Resolver404</Type><Message>{u'path': u'favicon.ico', u'tried': [[</Message><Frame><File>/project/virtenv/local/lib/python2.7/site-packages/django/core/handlers/base.py</File><Line>152</Line><Method>get_response</Method></Frame><Frame><File>/project/virtenv/local/lib/python2.7/site-packages/django/utils/decorators.py</File><Line>99</Line><Method>_wrapped_view</Method></Frame><Frame><File>/project/virtenv/local/lib/python2.7/site-packages/django/views/defaults.py</File><Line>30</Line><Method>page_not_found</Method></Frame><Frame><File>/project/virtenv/local/lib/python2.7/site-packages/debug_toolbar/panels/templates/panel.py</File><Line>55</Line><Method>_request_context__init__</Method></Frame><Frame><File>./project/context_processors.py</File><Line>88</Line><Method>app_delegate</Method></Frame><Frame><File>/project/virtenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py</File><Line>453</Line><Method>resolve</Method></Frame><Frame><File>/project/virtenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py</File><Line>333</Line><Method>resolve</Method></Frame></Stack></Post></Posts>